### ISSUE TITLE
Decide on format for redaction rules

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/ImageDePHI#2]
We want to have a set of redaction / passthrough rules for metadata and associated images.

Metadata has keys (potentially nested) and values.  Associated images have names ("label", "macro", "thumbnail").

The set of actions for images is probably:
- keep (but rewrite to ensure no leaked metadata within the image)
- remove 
- remove upper/left square
  This is used on macro images to ensure no label overflow is present.  Does this need to be more flexible?
- replace with new label (see below)
- augment with new label (see below)

In the SEER project, we add or replace label images with text that includes the output file name.  We probably want this to be a set of options: include filename and specific metadata in some formatted way.  Possibly include a barcode with the same information.  Data matrix barcodes are nominally the most popular.

The set of actions for metadata is probably:
- keep
- remove
- replace with a different piece of metadata (e.g., the output file name; an internal UUID for the patient)
- modify according to a set of rules (e.g., dates move to January 1 of the specified year in the format YYYY-MM-DD)

We may want the rules to be conditional on the input format or other properties.

One way to do this is to have a list of rules in a common format, such as yaml.  Each entry in the list would be a dictionary of values that could contain:
- type: "image" | "metadata"    # default is metadata
- key: \<exact name of image or metadata field>
- key_regex: \<regular expression to match image or metadata field>
- value: \<if set, only match this rule if the metadata value matches this exactly>
- value_regex: \<if set, only match this rule if the metadata value matches this expression>
- action: "keep" | "remove" | "replace" | <name of a defined action>   # the defined actions could be "dateToJan1", "removeSquare"
- action_options: \<object>  # a dictionary of fields to pass to the action if needed

Ultimately, if we find any images or metadata that DON'T match any rules, then we need instructions from the user on what to do.

This should probably be composable -- since it is a list, the load order is important, as that would allow rules to override each other in a predictable manner.  We want base rules that ignore things like image dimensions and other core fields that CANNOT be redacted.

If we are using large_Image to parse images and metadata, then the metadata dictionary is "<source>.getInternalMetadata()" with the key hierarchy flattened in some way for matching purposes.

**Comment by manthey** [comment]
@naglepuff @brianhelba @marySalvi Here are some initial thoughts on redaction rule sets.

**Comment by manthey** [comment]
We probably also want to predefine some value types so we don't have to repeat or add ugly regex for things.  That is, things like: `value_type` equal to one of `integer`, `float`, `array<float>`, ...   You can do this with references in the yaml, but that may be undesirable since we'll want the same sorts of values across different redaction rulesets.

**Comment by manthey** [comment]
The keys in the example are an abstraction from how large_image getInternalMetadata exposes information, though the Philips keys are more convoluted.  Further, the "dateToJan1" rule probably hides some complexity in the variations of how dates are stored for different fields; this is where the actionOptions might be appropriate.

**Comment by naglepuff** [comment]
Here is one possible rule file format as discussed with @brianhelba 

For each file format we want to support, we need a dictionary to specify how redaction should be preformed on those types of files. Each piece of metadata can correspond to either a dictionary, describing how it should be redacted, or a string, which is simply the action. This reduces boilerplate considering there are many tags that are automatically kept because they are required by the file spec, but still allows the flexibility of complex rules.

```
---
name: Base rules
description: These are the default rules for each potential piece of redactable material (metadata, image) to be used as a fallback if there are no user-defined rules for a piece of redactable material.
tiff:
  matches:
    - "*.tiff"
  image: keep
  preview_thumbnail: delete
  metadata:
    ImageWidth:
      action: keep
    NewSubfileType: keep
    ImageDescription: 
    32932: delete
    ...
svs:
  matches:
    - "*.svs"
  image: keep
  preview_thumbnail: delete
  metadata:
    ImageWidth: keep
    NewSubfileType: keep
    ...
  image_description:
    AppMag: keep
    ...
```
